export const products = [
  {id:'linen-shirt', name:'Linen Shirt', category:'Shirts', price:220000, compareAt:260000, image:'/images/linen-shirt-hero.jpg', thumb:'/images/linen-shirt.jpg', colors:['Natural','Black'], sizes:['S','M','L','XL'], stock:8, description:'A relaxed linen shirt with a classic collar, button-down front and an effortless drape for warm Kampala days.', fabric:'100% linen. Breathable, lightweight and pre-washed for softness.'},
  {id:'wool-trousers', name:'Wool Trousers', category:'Trousers', price:89000, image:'/images/wool-trousers.jpg', sizes:['S','M','L','XL'], stock:14, description:'Tailored wool trousers with a clean straight leg and a polished everyday finish.', fabric:'Wool blend with a soft, structured hand.'},
  {id:'cotton-tee', name:'Cotton Tee', category:'Tees', price:35000, image:'/images/cotton-tee.jpg', sizes:['S','M','L','XL'], stock:22, description:'An elevated everyday tee cut from smooth, heavyweight cotton.', fabric:'100% premium cotton.'},
  {id:'suede-jacket', name:'Suede Jacket', category:'Outerwear', price:129000, image:'/images/suede-jacket.jpg', sizes:['S','M','L','XL'], stock:4, description:'Soft suede outerwear with a minimal collar and versatile relaxed silhouette.', fabric:'Premium suede leather with a soft lining.'},
  {id:'knit-sweater', name:'Knit Sweater', category:'Knitwear', price:65000, image:'/images/knit-sweater.jpg', sizes:['S','M','L','XL'], stock:9, description:'A warm, refined knit designed for layering.', fabric:'Soft wool-blend knit.'},
  {id:'leather-belt', name:'Leather Belt', category:'Accessories', price:45000, image:'/images/leather-belt.jpg', sizes:['M','L'], stock:16, description:'Minimal leather belt with a polished buckle.', fabric:'Full-grain leather.'},
  {id:'cargo-pants', name:'Cargo Pants', category:'Trousers', price:78000, image:'/images/cargo-pants.jpg', sizes:['S','M','L','XL'], stock:12, description:'Utility-inspired trousers balanced with a clean premium cut.', fabric:'Cotton twill.'},
  {id:'loafers', name:'Leather Loafers', category:'Footwear', price:99000, image:'/images/loafers.jpg', sizes:['40','41','42','43','44'], stock:5, description:'Classic leather loafers with a refined low-profile shape.', fabric:'Leather upper with cushioned footbed.'},
  {id:'wool-overcoat', name:'Wool Blend Overcoat', category:'Outerwear', price:285000, image:'/images/suede-jacket.jpg', sizes:['S','M','L','XL'], stock:3, description:'A long tailored overcoat for understated statement dressing.', fabric:'Wool blend.'},
  {id:'tailored-coat', name:'Tailored Wool Coat', category:'Outerwear', price:320000, image:'/images/suede-jacket.jpg', sizes:['S','M','L','XL'], stock:6, description:'A sharply tailored wool coat with clean lines.', fabric:'Wool blend.'},
  {id:'classic-trench', name:'Classic Trench Coat', category:'Outerwear', price:260000, image:'/images/suede-jacket.jpg', sizes:['S','M','L','XL'], stock:7, description:'A timeless double-breasted trench in warm stone.', fabric:'Cotton blend.'},
  {id:'cotton-poplin', name:'Cotton Poplin Shirt', category:'Shirts', price:29900, image:'/images/cotton-tee.jpg', sizes:['S','M','L','XL'], stock:0, description:'Crisp poplin shirt for polished daily wear.', fabric:'100% cotton poplin.'}
]
export const getProduct = id => products.find(p => p.id === id)
